/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BannerPreventivo {
        "applicazione": string;
    }
    interface BckContattaci {
    }
    interface BottoneChiaro {
        /**
          * Bottone chiaro con lo sfondo #12A6E6
         */
        "btnTextChiaro": string;
    }
    interface BottoneFaq {
    }
    interface BottoneScuro {
        /**
          * Bottone scuro con lo sfondo #02336E
         */
        "btnTextScuro": string;
    }
    interface BoxCerchi {
        /**
          * contenitore cerchi con icone svg
         */
        "icona1": string;
        "icona2": string;
        "icona3": string;
    }
    interface BoxStaff {
        /**
          * contenitore cerchi con immagini dello sfaff dell'azienda
         */
        "staff1": string;
        "staff2": string;
        "staff3": string;
    }
    interface CampoContattaci {
    }
    interface ContainerBody {
    }
    interface ContainerCarte {
    }
    interface ContainerFaq {
    }
    interface ContattaciForm {
        "icona1": string;
    }
    interface ContattiNavigazione {
    }
    interface DidascaliaFooter {
    }
    interface FooterFooter {
    }
    interface HeaderPrincipale {
    }
    interface ImgLogo {
    }
    interface ListaContatti {
    }
    interface MenuPrincipale {
    }
    interface MobileMenu {
    }
    interface NavigazionePrincipale {
    }
    interface NewsSection {
    }
    interface OggettoMessaggio {
    }
    interface PrimaCarta {
    }
    interface PrimaImg {
    }
    interface PrimoBoxTesto {
    }
    interface QuartaCarta {
    }
    interface QuartaImmagine {
    }
    interface SecondaCarta {
    }
    interface SecondaImmagine {
    }
    interface SecondoBoxTesto {
    }
    interface SimpleText {
        /**
          * Prop per rendere il testo variabile all'interno del sito
         */
        "simpleText": string;
    }
    interface TerzaCarta {
    }
    interface TerzaImmagine {
    }
    interface TerzoBoxTesto {
    }
    interface TestoCalltoaction {
    }
    interface TestoContattaci {
    }
    interface TestoContatti {
    }
    interface TitoliCarte {
        /**
          * Prop per rendere variabile i titoli all'interno delle carte
         */
        "cardTitol": string;
    }
}
declare global {
    interface HTMLBannerPreventivoElement extends Components.BannerPreventivo, HTMLStencilElement {
    }
    var HTMLBannerPreventivoElement: {
        prototype: HTMLBannerPreventivoElement;
        new (): HTMLBannerPreventivoElement;
    };
    interface HTMLBckContattaciElement extends Components.BckContattaci, HTMLStencilElement {
    }
    var HTMLBckContattaciElement: {
        prototype: HTMLBckContattaciElement;
        new (): HTMLBckContattaciElement;
    };
    interface HTMLBottoneChiaroElement extends Components.BottoneChiaro, HTMLStencilElement {
    }
    var HTMLBottoneChiaroElement: {
        prototype: HTMLBottoneChiaroElement;
        new (): HTMLBottoneChiaroElement;
    };
    interface HTMLBottoneFaqElement extends Components.BottoneFaq, HTMLStencilElement {
    }
    var HTMLBottoneFaqElement: {
        prototype: HTMLBottoneFaqElement;
        new (): HTMLBottoneFaqElement;
    };
    interface HTMLBottoneScuroElement extends Components.BottoneScuro, HTMLStencilElement {
    }
    var HTMLBottoneScuroElement: {
        prototype: HTMLBottoneScuroElement;
        new (): HTMLBottoneScuroElement;
    };
    interface HTMLBoxCerchiElement extends Components.BoxCerchi, HTMLStencilElement {
    }
    var HTMLBoxCerchiElement: {
        prototype: HTMLBoxCerchiElement;
        new (): HTMLBoxCerchiElement;
    };
    interface HTMLBoxStaffElement extends Components.BoxStaff, HTMLStencilElement {
    }
    var HTMLBoxStaffElement: {
        prototype: HTMLBoxStaffElement;
        new (): HTMLBoxStaffElement;
    };
    interface HTMLCampoContattaciElement extends Components.CampoContattaci, HTMLStencilElement {
    }
    var HTMLCampoContattaciElement: {
        prototype: HTMLCampoContattaciElement;
        new (): HTMLCampoContattaciElement;
    };
    interface HTMLContainerBodyElement extends Components.ContainerBody, HTMLStencilElement {
    }
    var HTMLContainerBodyElement: {
        prototype: HTMLContainerBodyElement;
        new (): HTMLContainerBodyElement;
    };
    interface HTMLContainerCarteElement extends Components.ContainerCarte, HTMLStencilElement {
    }
    var HTMLContainerCarteElement: {
        prototype: HTMLContainerCarteElement;
        new (): HTMLContainerCarteElement;
    };
    interface HTMLContainerFaqElement extends Components.ContainerFaq, HTMLStencilElement {
    }
    var HTMLContainerFaqElement: {
        prototype: HTMLContainerFaqElement;
        new (): HTMLContainerFaqElement;
    };
    interface HTMLContattaciFormElement extends Components.ContattaciForm, HTMLStencilElement {
    }
    var HTMLContattaciFormElement: {
        prototype: HTMLContattaciFormElement;
        new (): HTMLContattaciFormElement;
    };
    interface HTMLContattiNavigazioneElement extends Components.ContattiNavigazione, HTMLStencilElement {
    }
    var HTMLContattiNavigazioneElement: {
        prototype: HTMLContattiNavigazioneElement;
        new (): HTMLContattiNavigazioneElement;
    };
    interface HTMLDidascaliaFooterElement extends Components.DidascaliaFooter, HTMLStencilElement {
    }
    var HTMLDidascaliaFooterElement: {
        prototype: HTMLDidascaliaFooterElement;
        new (): HTMLDidascaliaFooterElement;
    };
    interface HTMLFooterFooterElement extends Components.FooterFooter, HTMLStencilElement {
    }
    var HTMLFooterFooterElement: {
        prototype: HTMLFooterFooterElement;
        new (): HTMLFooterFooterElement;
    };
    interface HTMLHeaderPrincipaleElement extends Components.HeaderPrincipale, HTMLStencilElement {
    }
    var HTMLHeaderPrincipaleElement: {
        prototype: HTMLHeaderPrincipaleElement;
        new (): HTMLHeaderPrincipaleElement;
    };
    interface HTMLImgLogoElement extends Components.ImgLogo, HTMLStencilElement {
    }
    var HTMLImgLogoElement: {
        prototype: HTMLImgLogoElement;
        new (): HTMLImgLogoElement;
    };
    interface HTMLListaContattiElement extends Components.ListaContatti, HTMLStencilElement {
    }
    var HTMLListaContattiElement: {
        prototype: HTMLListaContattiElement;
        new (): HTMLListaContattiElement;
    };
    interface HTMLMenuPrincipaleElement extends Components.MenuPrincipale, HTMLStencilElement {
    }
    var HTMLMenuPrincipaleElement: {
        prototype: HTMLMenuPrincipaleElement;
        new (): HTMLMenuPrincipaleElement;
    };
    interface HTMLMobileMenuElement extends Components.MobileMenu, HTMLStencilElement {
    }
    var HTMLMobileMenuElement: {
        prototype: HTMLMobileMenuElement;
        new (): HTMLMobileMenuElement;
    };
    interface HTMLNavigazionePrincipaleElement extends Components.NavigazionePrincipale, HTMLStencilElement {
    }
    var HTMLNavigazionePrincipaleElement: {
        prototype: HTMLNavigazionePrincipaleElement;
        new (): HTMLNavigazionePrincipaleElement;
    };
    interface HTMLNewsSectionElement extends Components.NewsSection, HTMLStencilElement {
    }
    var HTMLNewsSectionElement: {
        prototype: HTMLNewsSectionElement;
        new (): HTMLNewsSectionElement;
    };
    interface HTMLOggettoMessaggioElement extends Components.OggettoMessaggio, HTMLStencilElement {
    }
    var HTMLOggettoMessaggioElement: {
        prototype: HTMLOggettoMessaggioElement;
        new (): HTMLOggettoMessaggioElement;
    };
    interface HTMLPrimaCartaElement extends Components.PrimaCarta, HTMLStencilElement {
    }
    var HTMLPrimaCartaElement: {
        prototype: HTMLPrimaCartaElement;
        new (): HTMLPrimaCartaElement;
    };
    interface HTMLPrimaImgElement extends Components.PrimaImg, HTMLStencilElement {
    }
    var HTMLPrimaImgElement: {
        prototype: HTMLPrimaImgElement;
        new (): HTMLPrimaImgElement;
    };
    interface HTMLPrimoBoxTestoElement extends Components.PrimoBoxTesto, HTMLStencilElement {
    }
    var HTMLPrimoBoxTestoElement: {
        prototype: HTMLPrimoBoxTestoElement;
        new (): HTMLPrimoBoxTestoElement;
    };
    interface HTMLQuartaCartaElement extends Components.QuartaCarta, HTMLStencilElement {
    }
    var HTMLQuartaCartaElement: {
        prototype: HTMLQuartaCartaElement;
        new (): HTMLQuartaCartaElement;
    };
    interface HTMLQuartaImmagineElement extends Components.QuartaImmagine, HTMLStencilElement {
    }
    var HTMLQuartaImmagineElement: {
        prototype: HTMLQuartaImmagineElement;
        new (): HTMLQuartaImmagineElement;
    };
    interface HTMLSecondaCartaElement extends Components.SecondaCarta, HTMLStencilElement {
    }
    var HTMLSecondaCartaElement: {
        prototype: HTMLSecondaCartaElement;
        new (): HTMLSecondaCartaElement;
    };
    interface HTMLSecondaImmagineElement extends Components.SecondaImmagine, HTMLStencilElement {
    }
    var HTMLSecondaImmagineElement: {
        prototype: HTMLSecondaImmagineElement;
        new (): HTMLSecondaImmagineElement;
    };
    interface HTMLSecondoBoxTestoElement extends Components.SecondoBoxTesto, HTMLStencilElement {
    }
    var HTMLSecondoBoxTestoElement: {
        prototype: HTMLSecondoBoxTestoElement;
        new (): HTMLSecondoBoxTestoElement;
    };
    interface HTMLSimpleTextElement extends Components.SimpleText, HTMLStencilElement {
    }
    var HTMLSimpleTextElement: {
        prototype: HTMLSimpleTextElement;
        new (): HTMLSimpleTextElement;
    };
    interface HTMLTerzaCartaElement extends Components.TerzaCarta, HTMLStencilElement {
    }
    var HTMLTerzaCartaElement: {
        prototype: HTMLTerzaCartaElement;
        new (): HTMLTerzaCartaElement;
    };
    interface HTMLTerzaImmagineElement extends Components.TerzaImmagine, HTMLStencilElement {
    }
    var HTMLTerzaImmagineElement: {
        prototype: HTMLTerzaImmagineElement;
        new (): HTMLTerzaImmagineElement;
    };
    interface HTMLTerzoBoxTestoElement extends Components.TerzoBoxTesto, HTMLStencilElement {
    }
    var HTMLTerzoBoxTestoElement: {
        prototype: HTMLTerzoBoxTestoElement;
        new (): HTMLTerzoBoxTestoElement;
    };
    interface HTMLTestoCalltoactionElement extends Components.TestoCalltoaction, HTMLStencilElement {
    }
    var HTMLTestoCalltoactionElement: {
        prototype: HTMLTestoCalltoactionElement;
        new (): HTMLTestoCalltoactionElement;
    };
    interface HTMLTestoContattaciElement extends Components.TestoContattaci, HTMLStencilElement {
    }
    var HTMLTestoContattaciElement: {
        prototype: HTMLTestoContattaciElement;
        new (): HTMLTestoContattaciElement;
    };
    interface HTMLTestoContattiElement extends Components.TestoContatti, HTMLStencilElement {
    }
    var HTMLTestoContattiElement: {
        prototype: HTMLTestoContattiElement;
        new (): HTMLTestoContattiElement;
    };
    interface HTMLTitoliCarteElement extends Components.TitoliCarte, HTMLStencilElement {
    }
    var HTMLTitoliCarteElement: {
        prototype: HTMLTitoliCarteElement;
        new (): HTMLTitoliCarteElement;
    };
    interface HTMLElementTagNameMap {
        "banner-preventivo": HTMLBannerPreventivoElement;
        "bck-contattaci": HTMLBckContattaciElement;
        "bottone-chiaro": HTMLBottoneChiaroElement;
        "bottone-faq": HTMLBottoneFaqElement;
        "bottone-scuro": HTMLBottoneScuroElement;
        "box-cerchi": HTMLBoxCerchiElement;
        "box-staff": HTMLBoxStaffElement;
        "campo-contattaci": HTMLCampoContattaciElement;
        "container-body": HTMLContainerBodyElement;
        "container-carte": HTMLContainerCarteElement;
        "container-faq": HTMLContainerFaqElement;
        "contattaci-form": HTMLContattaciFormElement;
        "contatti-navigazione": HTMLContattiNavigazioneElement;
        "didascalia-footer": HTMLDidascaliaFooterElement;
        "footer-footer": HTMLFooterFooterElement;
        "header-principale": HTMLHeaderPrincipaleElement;
        "img-logo": HTMLImgLogoElement;
        "lista-contatti": HTMLListaContattiElement;
        "menu-principale": HTMLMenuPrincipaleElement;
        "mobile-menu": HTMLMobileMenuElement;
        "navigazione-principale": HTMLNavigazionePrincipaleElement;
        "news-section": HTMLNewsSectionElement;
        "oggetto-messaggio": HTMLOggettoMessaggioElement;
        "prima-carta": HTMLPrimaCartaElement;
        "prima-img": HTMLPrimaImgElement;
        "primo-box-testo": HTMLPrimoBoxTestoElement;
        "quarta-carta": HTMLQuartaCartaElement;
        "quarta-immagine": HTMLQuartaImmagineElement;
        "seconda-carta": HTMLSecondaCartaElement;
        "seconda-immagine": HTMLSecondaImmagineElement;
        "secondo-box-testo": HTMLSecondoBoxTestoElement;
        "simple-text": HTMLSimpleTextElement;
        "terza-carta": HTMLTerzaCartaElement;
        "terza-immagine": HTMLTerzaImmagineElement;
        "terzo-box-testo": HTMLTerzoBoxTestoElement;
        "testo-calltoaction": HTMLTestoCalltoactionElement;
        "testo-contattaci": HTMLTestoContattaciElement;
        "testo-contatti": HTMLTestoContattiElement;
        "titoli-carte": HTMLTitoliCarteElement;
    }
}
declare namespace LocalJSX {
    interface BannerPreventivo {
        "applicazione"?: string;
    }
    interface BckContattaci {
    }
    interface BottoneChiaro {
        /**
          * Bottone chiaro con lo sfondo #12A6E6
         */
        "btnTextChiaro"?: string;
    }
    interface BottoneFaq {
    }
    interface BottoneScuro {
        /**
          * Bottone scuro con lo sfondo #02336E
         */
        "btnTextScuro"?: string;
    }
    interface BoxCerchi {
        /**
          * contenitore cerchi con icone svg
         */
        "icona1"?: string;
        "icona2"?: string;
        "icona3"?: string;
    }
    interface BoxStaff {
        /**
          * contenitore cerchi con immagini dello sfaff dell'azienda
         */
        "staff1"?: string;
        "staff2"?: string;
        "staff3"?: string;
    }
    interface CampoContattaci {
    }
    interface ContainerBody {
    }
    interface ContainerCarte {
    }
    interface ContainerFaq {
    }
    interface ContattaciForm {
        "icona1"?: string;
    }
    interface ContattiNavigazione {
    }
    interface DidascaliaFooter {
    }
    interface FooterFooter {
    }
    interface HeaderPrincipale {
    }
    interface ImgLogo {
    }
    interface ListaContatti {
    }
    interface MenuPrincipale {
    }
    interface MobileMenu {
    }
    interface NavigazionePrincipale {
    }
    interface NewsSection {
    }
    interface OggettoMessaggio {
    }
    interface PrimaCarta {
    }
    interface PrimaImg {
    }
    interface PrimoBoxTesto {
    }
    interface QuartaCarta {
    }
    interface QuartaImmagine {
    }
    interface SecondaCarta {
    }
    interface SecondaImmagine {
    }
    interface SecondoBoxTesto {
    }
    interface SimpleText {
        /**
          * Prop per rendere il testo variabile all'interno del sito
         */
        "simpleText"?: string;
    }
    interface TerzaCarta {
    }
    interface TerzaImmagine {
    }
    interface TerzoBoxTesto {
    }
    interface TestoCalltoaction {
    }
    interface TestoContattaci {
    }
    interface TestoContatti {
    }
    interface TitoliCarte {
        /**
          * Prop per rendere variabile i titoli all'interno delle carte
         */
        "cardTitol"?: string;
    }
    interface IntrinsicElements {
        "banner-preventivo": BannerPreventivo;
        "bck-contattaci": BckContattaci;
        "bottone-chiaro": BottoneChiaro;
        "bottone-faq": BottoneFaq;
        "bottone-scuro": BottoneScuro;
        "box-cerchi": BoxCerchi;
        "box-staff": BoxStaff;
        "campo-contattaci": CampoContattaci;
        "container-body": ContainerBody;
        "container-carte": ContainerCarte;
        "container-faq": ContainerFaq;
        "contattaci-form": ContattaciForm;
        "contatti-navigazione": ContattiNavigazione;
        "didascalia-footer": DidascaliaFooter;
        "footer-footer": FooterFooter;
        "header-principale": HeaderPrincipale;
        "img-logo": ImgLogo;
        "lista-contatti": ListaContatti;
        "menu-principale": MenuPrincipale;
        "mobile-menu": MobileMenu;
        "navigazione-principale": NavigazionePrincipale;
        "news-section": NewsSection;
        "oggetto-messaggio": OggettoMessaggio;
        "prima-carta": PrimaCarta;
        "prima-img": PrimaImg;
        "primo-box-testo": PrimoBoxTesto;
        "quarta-carta": QuartaCarta;
        "quarta-immagine": QuartaImmagine;
        "seconda-carta": SecondaCarta;
        "seconda-immagine": SecondaImmagine;
        "secondo-box-testo": SecondoBoxTesto;
        "simple-text": SimpleText;
        "terza-carta": TerzaCarta;
        "terza-immagine": TerzaImmagine;
        "terzo-box-testo": TerzoBoxTesto;
        "testo-calltoaction": TestoCalltoaction;
        "testo-contattaci": TestoContattaci;
        "testo-contatti": TestoContatti;
        "titoli-carte": TitoliCarte;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "banner-preventivo": LocalJSX.BannerPreventivo & JSXBase.HTMLAttributes<HTMLBannerPreventivoElement>;
            "bck-contattaci": LocalJSX.BckContattaci & JSXBase.HTMLAttributes<HTMLBckContattaciElement>;
            "bottone-chiaro": LocalJSX.BottoneChiaro & JSXBase.HTMLAttributes<HTMLBottoneChiaroElement>;
            "bottone-faq": LocalJSX.BottoneFaq & JSXBase.HTMLAttributes<HTMLBottoneFaqElement>;
            "bottone-scuro": LocalJSX.BottoneScuro & JSXBase.HTMLAttributes<HTMLBottoneScuroElement>;
            "box-cerchi": LocalJSX.BoxCerchi & JSXBase.HTMLAttributes<HTMLBoxCerchiElement>;
            "box-staff": LocalJSX.BoxStaff & JSXBase.HTMLAttributes<HTMLBoxStaffElement>;
            "campo-contattaci": LocalJSX.CampoContattaci & JSXBase.HTMLAttributes<HTMLCampoContattaciElement>;
            "container-body": LocalJSX.ContainerBody & JSXBase.HTMLAttributes<HTMLContainerBodyElement>;
            "container-carte": LocalJSX.ContainerCarte & JSXBase.HTMLAttributes<HTMLContainerCarteElement>;
            "container-faq": LocalJSX.ContainerFaq & JSXBase.HTMLAttributes<HTMLContainerFaqElement>;
            "contattaci-form": LocalJSX.ContattaciForm & JSXBase.HTMLAttributes<HTMLContattaciFormElement>;
            "contatti-navigazione": LocalJSX.ContattiNavigazione & JSXBase.HTMLAttributes<HTMLContattiNavigazioneElement>;
            "didascalia-footer": LocalJSX.DidascaliaFooter & JSXBase.HTMLAttributes<HTMLDidascaliaFooterElement>;
            "footer-footer": LocalJSX.FooterFooter & JSXBase.HTMLAttributes<HTMLFooterFooterElement>;
            "header-principale": LocalJSX.HeaderPrincipale & JSXBase.HTMLAttributes<HTMLHeaderPrincipaleElement>;
            "img-logo": LocalJSX.ImgLogo & JSXBase.HTMLAttributes<HTMLImgLogoElement>;
            "lista-contatti": LocalJSX.ListaContatti & JSXBase.HTMLAttributes<HTMLListaContattiElement>;
            "menu-principale": LocalJSX.MenuPrincipale & JSXBase.HTMLAttributes<HTMLMenuPrincipaleElement>;
            "mobile-menu": LocalJSX.MobileMenu & JSXBase.HTMLAttributes<HTMLMobileMenuElement>;
            "navigazione-principale": LocalJSX.NavigazionePrincipale & JSXBase.HTMLAttributes<HTMLNavigazionePrincipaleElement>;
            "news-section": LocalJSX.NewsSection & JSXBase.HTMLAttributes<HTMLNewsSectionElement>;
            "oggetto-messaggio": LocalJSX.OggettoMessaggio & JSXBase.HTMLAttributes<HTMLOggettoMessaggioElement>;
            "prima-carta": LocalJSX.PrimaCarta & JSXBase.HTMLAttributes<HTMLPrimaCartaElement>;
            "prima-img": LocalJSX.PrimaImg & JSXBase.HTMLAttributes<HTMLPrimaImgElement>;
            "primo-box-testo": LocalJSX.PrimoBoxTesto & JSXBase.HTMLAttributes<HTMLPrimoBoxTestoElement>;
            "quarta-carta": LocalJSX.QuartaCarta & JSXBase.HTMLAttributes<HTMLQuartaCartaElement>;
            "quarta-immagine": LocalJSX.QuartaImmagine & JSXBase.HTMLAttributes<HTMLQuartaImmagineElement>;
            "seconda-carta": LocalJSX.SecondaCarta & JSXBase.HTMLAttributes<HTMLSecondaCartaElement>;
            "seconda-immagine": LocalJSX.SecondaImmagine & JSXBase.HTMLAttributes<HTMLSecondaImmagineElement>;
            "secondo-box-testo": LocalJSX.SecondoBoxTesto & JSXBase.HTMLAttributes<HTMLSecondoBoxTestoElement>;
            "simple-text": LocalJSX.SimpleText & JSXBase.HTMLAttributes<HTMLSimpleTextElement>;
            "terza-carta": LocalJSX.TerzaCarta & JSXBase.HTMLAttributes<HTMLTerzaCartaElement>;
            "terza-immagine": LocalJSX.TerzaImmagine & JSXBase.HTMLAttributes<HTMLTerzaImmagineElement>;
            "terzo-box-testo": LocalJSX.TerzoBoxTesto & JSXBase.HTMLAttributes<HTMLTerzoBoxTestoElement>;
            "testo-calltoaction": LocalJSX.TestoCalltoaction & JSXBase.HTMLAttributes<HTMLTestoCalltoactionElement>;
            "testo-contattaci": LocalJSX.TestoContattaci & JSXBase.HTMLAttributes<HTMLTestoContattaciElement>;
            "testo-contatti": LocalJSX.TestoContatti & JSXBase.HTMLAttributes<HTMLTestoContattiElement>;
            "titoli-carte": LocalJSX.TitoliCarte & JSXBase.HTMLAttributes<HTMLTitoliCarteElement>;
        }
    }
}
